name: multi_select_dropdown
description: A customizable multi-select dropdown for Flutter applications.
version: 0.0.1
repository: https://github.com/karanrana097/multi_select_dropdown
homepage: https://github.com/karanrana097/multi_select_dropdown

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
