name: multi_select_dropdown
description: A customizable multi-select dropdown widget for Flutter apps.
version: 0.0.1
homepage: https://github.com/your-repo/multi_select_dropdown
repository: https://github.com/your-repo/multi_select_dropdown
issue_tracker: https://github.com/your-repo/multi_select_dropdown/issues
author: Karan Rana
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
